# .github/actions/ocaml-lint/action.yaml
---
name: OCaml lint checks
description: OCaml Lints; Check-format, Require-ppx-version

runs:
  using: "composite"
  steps:
    - run: |
        ./buildkite/scripts/lint-check-format.sh && ./scripts/require-ppxs.py
      shell: bash
