# .github/actions/validation-service/action.yaml
---
name: Validation Service
description: Validation service lint steps; employs various forms static analysis on the elixir codebase

runs:
  using: 'docker'
  image: 'elixir:1.10-alpine'
  entrypoint: sh
  args:
    - -c
    - cd src/app/validation && mix local.hex --force && mix local.rebar --force && mix deps.get && mix check --force